// Code generated by MockGen. DO NOT EDIT.
// Source: msk.go
//
// Generated by this command:
//
//	mockgen -source=msk.go -destination ../mocks/msk.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kafka "github.com/aws/aws-sdk-go-v2/service/kafka"
	gomock "go.uber.org/mock/gomock"
)

// MockMSK is a mock of MSK interface.
type MockMSK struct {
	ctrl     *gomock.Controller
	recorder *MockMSKMockRecorder
	isgomock struct{}
}

// MockMSKMockRecorder is the mock recorder for MockMSK.
type MockMSKMockRecorder struct {
	mock *MockMSK
}

// NewMockMSK creates a new mock instance.
func NewMockMSK(ctrl *gomock.Controller) *MockMSK {
	mock := &MockMSK{ctrl: ctrl}
	mock.recorder = &MockMSKMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMSK) EXPECT() *MockMSKMockRecorder {
	return m.recorder
}

// ListClustersV2 mocks base method.
func (m *MockMSK) ListClustersV2(ctx context.Context, input *kafka.ListClustersV2Input, optFns ...func(*kafka.Options)) (*kafka.ListClustersV2Output, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListClustersV2", varargs...)
	ret0, _ := ret[0].(*kafka.ListClustersV2Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClustersV2 indicates an expected call of ListClustersV2.
func (mr *MockMSKMockRecorder) ListClustersV2(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClustersV2", reflect.TypeOf((*MockMSK)(nil).ListClustersV2), varargs...)
}
