name: Bug Report
description: File a bug report
type: "bug"
projects: ["grafana/513"] # Platform Monitoring
body:
  - type: input
    id: cloudcost-exporter-version
    attributes:
      label: CloudCost Exporter Version
  - type: input
    id: csp
    attributes:
      label: Cloud Provider
  - type: textarea
    id: affected_modules
    attributes:
      label: Affected Modules(s)
      placeholder: |
        * eks|gke|aks
        * s3|gcs
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: |
        What should have happened?
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      placeholder: |
        What actually happened?
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        Please list the steps required to reproduce the issue.
  - type: textarea
    id: important_factoids
    attributes:
      label: Important Factoids
      placeholder: |
        Are there anything atypical about your cloudcost-exporter setup? In which kind of Kubernetes cluster does it run?
  - type: textarea
    id: references
    attributes:
      label: References
      placeholder: |
        Include a list of references to support the bug.
