name: Feature Request
description: Suggest an idea for CloudCost Exporter
type: "enhancement"
projects: ["grafana/513"] # Platform Monitoring
body:
  - type: input
    id: csp
    attributes:
      label: Cloud Provider
  - type: textarea
    id: request
    attributes:
      label: Feature Request
      placeholder: |
        What would you like to see added to the Grafana provider?
