// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-09-19 10:52:30.823443758 -0300 -03 m=+1.591151834

package aks

import "strings"


// getPremiumSSDSKU returns the Azure disk SKU name for Premium SSD based on disk size.
// Auto-generated from Azure Retail Prices API disk pricing tiers.
func (ds *DiskStore) getPremiumSSDSKU(sizeGB int32) string {
	if sizeGB <= 32 {
		return "P4 LRS Disk" // 32GB
	} else if sizeGB <= 64 {
		return "P6 LRS Disk" // 64GB
	} else if sizeGB <= 128 {
		return "P10 LRS Disk" // 128GB
	} else if sizeGB <= 256 {
		return "P15 LRS Disk" // 256GB
	} else if sizeGB <= 512 {
		return "P20 LRS Disk" // 512GB
	} else if sizeGB <= 1024 {
		return "P30 LRS Disk" // 1024GB
	} else if sizeGB <= 2048 {
		return "P40 LRS Disk" // 2048GB
	} else if sizeGB <= 4096 {
		return "P50 LRS Disk" // 4096GB
	} else if sizeGB <= 8192 {
		return "P60 LRS Disk" // 8192GB
	} else if sizeGB <= 16384 {
		return "P70 LRS Disk" // 16384GB
	} else if sizeGB <= 32768 {
		return "P80 LRS Disk" // 32768GB
	} else {
		return "P80 LRS Disk" // Fallback for very large disks
	}
}

// getStandardHDDSKU returns the Azure disk SKU name for Standard HDD based on disk size.
// Auto-generated from Azure Retail Prices API disk pricing tiers.
func (ds *DiskStore) getStandardHDDSKU(sizeGB int32) string {
	if sizeGB <= 32 {
		return "S4 LRS Disk" // 32GB
	} else if sizeGB <= 64 {
		return "S6 LRS Disk" // 64GB
	} else if sizeGB <= 128 {
		return "S10 LRS Disk" // 128GB
	} else if sizeGB <= 256 {
		return "S15 LRS Disk" // 256GB
	} else if sizeGB <= 512 {
		return "S20 LRS Disk" // 512GB
	} else if sizeGB <= 1024 {
		return "S30 LRS Disk" // 1024GB
	} else if sizeGB <= 2048 {
		return "S40 LRS Disk" // 2048GB
	} else if sizeGB <= 4096 {
		return "S50 LRS Disk" // 4096GB
	} else if sizeGB <= 8192 {
		return "S60 LRS Disk" // 8192GB
	} else if sizeGB <= 16384 {
		return "S70 LRS Disk" // 16384GB
	} else if sizeGB <= 32768 {
		return "S80 LRS Disk" // 32768GB
	} else {
		return "S80 LRS Disk" // Fallback for very large disks
	}
}

// getStandardSSDSKU returns the Azure disk SKU name for Standard SSD based on disk size.
// Auto-generated from Azure Retail Prices API disk pricing tiers.
func (ds *DiskStore) getStandardSSDSKU(sizeGB int32) string {
	if sizeGB <= 4 {
		return "E1 LRS Disk" // 4GB
	} else if sizeGB <= 8 {
		return "E2 LRS Disk" // 8GB
	} else if sizeGB <= 16 {
		return "E3 LRS Disk" // 16GB
	} else if sizeGB <= 32 {
		return "E4 LRS Disk" // 32GB
	} else if sizeGB <= 64 {
		return "E6 LRS Disk" // 64GB
	} else if sizeGB <= 128 {
		return "E10 LRS Disk" // 128GB
	} else if sizeGB <= 256 {
		return "E15 LRS Disk" // 256GB
	} else if sizeGB <= 512 {
		return "E20 LRS Disk" // 512GB
	} else if sizeGB <= 1024 {
		return "E30 LRS Disk" // 1024GB
	} else if sizeGB <= 2048 {
		return "E40 LRS Disk" // 2048GB
	} else if sizeGB <= 4096 {
		return "E50 LRS Disk" // 4096GB
	} else if sizeGB <= 8192 {
		return "E60 LRS Disk" // 8192GB
	} else if sizeGB <= 16384 {
		return "E70 LRS Disk" // 16384GB
	} else if sizeGB <= 32768 {
		return "E80 LRS Disk" // 32768GB
	} else {
		return "E80 LRS Disk" // Fallback for very large disks
	}
}


// extractTierFromSKU extracts the pricing tier from a disk SKU name.
// Auto-generated helper function.
func extractTierFromSKU(sku string) string {
	parts := strings.Fields(sku)
	if len(parts) > 0 {
		return parts[0]
	}
	return "Unknown"
}
