// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-11-21 13:22:28.627195 +0100 CET m=+0.559821223

package aks

// mapClusterRegionToPricingRegion maps Azure cluster region names to Azure Retail Prices API region names.
// The pricing API uses different region naming conventions than ARM resources.
// Example: "centralus" (ARM) -> "US Central" (Pricing API)
//
// This function is auto-generated from the Azure Retail Prices API.
// To regenerate: go generate ./pkg/azure/aks
func (ds *DiskStore) mapClusterRegionToPricingRegion(clusterRegion string) string {
	// Generated mapping based on Azure Retail Prices API region names
	regionMap := map[string]string{
		"Global": "Global", // Auto-generated: Global -> Global
		"US Gov Zone 1": "US Gov Zone 1", // Auto-generated: US Gov Zone 1 -> US Gov Zone 1
		"Zone 2": "Zone 2", // Auto-generated: Zone 2 -> Zone 2
		"attatlanta1": "ATT Atlanta 1", // Auto-generated: attatlanta1 -> ATT Atlanta 1
		"attdallas1": "ATT Dallas 1", // Auto-generated: attdallas1 -> ATT Dallas 1
		"attdetroit1": "ATT Detroit 1", // Auto-generated: attdetroit1 -> ATT Detroit 1
		"australiacentral": "AU Central", // Auto-generated: australiacentral -> AU Central
		"australiacentral2": "AU Central 2", // Auto-generated: australiacentral2 -> AU Central 2
		"australiaeast": "AU East", // Auto-generated: australiaeast -> AU East
		"australiasoutheast": "AU Southeast", // Auto-generated: australiasoutheast -> AU Southeast
		"belgiumcentral": "BE Central", // Auto-generated: belgiumcentral -> BE Central
		"brazilsouth": "BR South", // Auto-generated: brazilsouth -> BR South
		"brazilsoutheast": "BR Southeast", // Auto-generated: brazilsoutheast -> BR Southeast
		"canadacentral": "CA Central", // Auto-generated: canadacentral -> CA Central
		"canadaeast": "CA East", // Auto-generated: canadaeast -> CA East
		"centralindia": "IN Central", // Auto-generated: centralindia -> IN Central
		"centralus": "US Central", // Auto-generated: centralus -> US Central
		"chilecentral": "CL Central", // Auto-generated: chilecentral -> CL Central
		"eastasia": "AP East", // Auto-generated: eastasia -> AP East
		"eastus": "US East", // Auto-generated: eastus -> US East
		"eastus2": "US East 2", // Auto-generated: eastus2 -> US East 2
		"francecentral": "FR Central", // Auto-generated: francecentral -> FR Central
		"francesouth": "FR South", // Auto-generated: francesouth -> FR South
		"germanynorth": "DE North", // Auto-generated: germanynorth -> DE North
		"germanywestcentral": "DE West Central", // Auto-generated: germanywestcentral -> DE West Central
		"indonesiacentral": "ID Central", // Auto-generated: indonesiacentral -> ID Central
		"israelcentral": "IL Central", // Auto-generated: israelcentral -> IL Central
		"israelnorthwest": "IL Northwest", // Auto-generated: israelnorthwest -> IL Northwest
		"italynorth": "IT North", // Auto-generated: italynorth -> IT North
		"japaneast": "JA East", // Auto-generated: japaneast -> JA East
		"japanwest": "JA West", // Auto-generated: japanwest -> JA West
		"jioindiacentral": "IN Central Jio", // Auto-generated: jioindiacentral -> IN Central Jio
		"jioindiawest": "IN West Jio", // Auto-generated: jioindiawest -> IN West Jio
		"koreacentral": "KR Central", // Auto-generated: koreacentral -> KR Central
		"koreasouth": "KR South", // Auto-generated: koreasouth -> KR South
		"malaysiawest": "MY West", // Auto-generated: malaysiawest -> MY West
		"mexicocentral": "MX Central", // Auto-generated: mexicocentral -> MX Central
		"newzealandnorth": "NZ North", // Auto-generated: newzealandnorth -> NZ North
		"northcentralus": "US North Central", // Auto-generated: northcentralus -> US North Central
		"northeurope": "EU North", // Auto-generated: northeurope -> EU North
		"norwayeast": "NO East", // Auto-generated: norwayeast -> NO East
		"norwaywest": "NO West", // Auto-generated: norwaywest -> NO West
		"polandcentral": "PL Central", // Auto-generated: polandcentral -> PL Central
		"qatarcentral": "QA Central", // Auto-generated: qatarcentral -> QA Central
		"southafricanorth": "ZA North", // Auto-generated: southafricanorth -> ZA North
		"southafricawest": "ZA West", // Auto-generated: southafricawest -> ZA West
		"southcentralus": "US South Central", // Auto-generated: southcentralus -> US South Central
		"southeastasia": "AP Southeast", // Auto-generated: southeastasia -> AP Southeast
		"southindia": "IN South", // Auto-generated: southindia -> IN South
		"spaincentral": "ES Central", // Auto-generated: spaincentral -> ES Central
		"swedencentral": "SE Central", // Auto-generated: swedencentral -> SE Central
		"swedensouth": "SE South", // Auto-generated: swedensouth -> SE South
		"switzerlandnorth": "CH North", // Auto-generated: switzerlandnorth -> CH North
		"switzerlandwest": "CH West", // Auto-generated: switzerlandwest -> CH West
		"taiwannorthwest": "TW Northwest", // Auto-generated: taiwannorthwest -> TW Northwest
		"uaecentral": "AE Central", // Auto-generated: uaecentral -> AE Central
		"uaenorth": "AE North", // Auto-generated: uaenorth -> AE North
		"uksouth": "UK South", // Auto-generated: uksouth -> UK South
		"ukwest": "UK West", // Auto-generated: ukwest -> UK West
		"usgovarizona": "US Gov AZ", // Auto-generated: usgovarizona -> US Gov AZ
		"usgovtexas": "US Gov TX", // Auto-generated: usgovtexas -> US Gov TX
		"usgovvirginia": "US Gov Virginia", // Auto-generated: usgovvirginia -> US Gov Virginia
		"westcentralus": "US West Central", // Auto-generated: westcentralus -> US West Central
		"westeurope": "EU West", // Auto-generated: westeurope -> EU West
		"westindia": "IN West", // Auto-generated: westindia -> IN West
		"westus": "US West", // Auto-generated: westus -> US West
		"westus2": "US West 2", // Auto-generated: westus2 -> US West 2
		"westus3": "US West 3", // Auto-generated: westus3 -> US West 3
	}

	if pricingRegion, ok := regionMap[clusterRegion]; ok {
		return pricingRegion
	}

	// Fallback: return the original region name if no mapping found
	// This allows the system to continue working with new regions
	return clusterRegion
}
