// Code generated by mockery v2.43.2. DO NOT EDIT.

package provider

import (
	prometheus "github.com/prometheus/client_golang/prometheus"
	mock "github.com/stretchr/testify/mock"
)

// Collector is an autogenerated mock type for the Collector type
type Collector struct {
	mock.Mock
}

type Collector_Expecter struct {
	mock *mock.Mock
}

func (_m *Collector) EXPECT() *Collector_Expecter {
	return &Collector_Expecter{mock: &_m.Mock}
}

// CheckReadiness provides a mock function with given fields:
func (_m *Collector) CheckReadiness() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckReadiness")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Collector_CheckReadiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckReadiness'
type Collector_CheckReadiness_Call struct {
	*mock.Call
}

// CheckReadiness is a helper method to define mock.On call
func (_e *Collector_Expecter) CheckReadiness() *Collector_CheckReadiness_Call {
	return &Collector_CheckReadiness_Call{Call: _e.mock.On("CheckReadiness")}
}

func (_c *Collector_CheckReadiness_Call) Run(run func()) *Collector_CheckReadiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Collector_CheckReadiness_Call) Return(_a0 bool) *Collector_CheckReadiness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Collector_CheckReadiness_Call) RunAndReturn(run func() bool) *Collector_CheckReadiness_Call {
	_c.Call.Return(run)
	return _c
}

// Collect provides a mock function with given fields: _a0
func (_m *Collector) Collect(_a0 chan<- prometheus.Metric) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Collect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(chan<- prometheus.Metric) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Collector_Collect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collect'
type Collector_Collect_Call struct {
	*mock.Call
}

// Collect is a helper method to define mock.On call
//   - _a0 chan<- prometheus.Metric
func (_e *Collector_Expecter) Collect(_a0 interface{}) *Collector_Collect_Call {
	return &Collector_Collect_Call{Call: _e.mock.On("Collect", _a0)}
}

func (_c *Collector_Collect_Call) Run(run func(_a0 chan<- prometheus.Metric)) *Collector_Collect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chan<- prometheus.Metric))
	})
	return _c
}

func (_c *Collector_Collect_Call) Return(_a0 error) *Collector_Collect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Collector_Collect_Call) RunAndReturn(run func(chan<- prometheus.Metric) error) *Collector_Collect_Call {
	_c.Call.Return(run)
	return _c
}

// CollectMetrics provides a mock function with given fields: _a0
func (_m *Collector) CollectMetrics(_a0 chan<- prometheus.Metric) float64 {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CollectMetrics")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(chan<- prometheus.Metric) float64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// Collector_CollectMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectMetrics'
type Collector_CollectMetrics_Call struct {
	*mock.Call
}

// CollectMetrics is a helper method to define mock.On call
//   - _a0 chan<- prometheus.Metric
func (_e *Collector_Expecter) CollectMetrics(_a0 interface{}) *Collector_CollectMetrics_Call {
	return &Collector_CollectMetrics_Call{Call: _e.mock.On("CollectMetrics", _a0)}
}

func (_c *Collector_CollectMetrics_Call) Run(run func(_a0 chan<- prometheus.Metric)) *Collector_CollectMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chan<- prometheus.Metric))
	})
	return _c
}

func (_c *Collector_CollectMetrics_Call) Return(_a0 float64) *Collector_CollectMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Collector_CollectMetrics_Call) RunAndReturn(run func(chan<- prometheus.Metric) float64) *Collector_CollectMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// Describe provides a mock function with given fields: _a0
func (_m *Collector) Describe(_a0 chan<- *prometheus.Desc) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Describe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(chan<- *prometheus.Desc) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Collector_Describe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Describe'
type Collector_Describe_Call struct {
	*mock.Call
}

// Describe is a helper method to define mock.On call
//   - _a0 chan<- *prometheus.Desc
func (_e *Collector_Expecter) Describe(_a0 interface{}) *Collector_Describe_Call {
	return &Collector_Describe_Call{Call: _e.mock.On("Describe", _a0)}
}

func (_c *Collector_Describe_Call) Run(run func(_a0 chan<- *prometheus.Desc)) *Collector_Describe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chan<- *prometheus.Desc))
	})
	return _c
}

func (_c *Collector_Describe_Call) Return(_a0 error) *Collector_Describe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Collector_Describe_Call) RunAndReturn(run func(chan<- *prometheus.Desc) error) *Collector_Describe_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *Collector) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Collector_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Collector_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Collector_Expecter) Name() *Collector_Name_Call {
	return &Collector_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Collector_Name_Call) Run(run func()) *Collector_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Collector_Name_Call) Return(_a0 string) *Collector_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Collector_Name_Call) RunAndReturn(run func() string) *Collector_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: r
func (_m *Collector) Register(r Registry) error {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(Registry) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Collector_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Collector_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - r Registry
func (_e *Collector_Expecter) Register(r interface{}) *Collector_Register_Call {
	return &Collector_Register_Call{Call: _e.mock.On("Register", r)}
}

func (_c *Collector_Register_Call) Run(run func(r Registry)) *Collector_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Registry))
	})
	return _c
}

func (_c *Collector_Register_Call) Return(_a0 error) *Collector_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Collector_Register_Call) RunAndReturn(run func(Registry) error) *Collector_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewCollector creates a new instance of Collector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Collector {
	mock := &Collector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
