// Code generated by mockery v2.43.2. DO NOT EDIT.

package pricing

import (
	context "context"

	servicepricing "github.com/aws/aws-sdk-go-v2/service/pricing"
	mock "github.com/stretchr/testify/mock"
)

// Pricing is an autogenerated mock type for the Pricing type
type Pricing struct {
	mock.Mock
}

type Pricing_Expecter struct {
	mock *mock.Mock
}

func (_m *Pricing) EXPECT() *Pricing_Expecter {
	return &Pricing_Expecter{mock: &_m.Mock}
}

// GetProducts provides a mock function with given fields: ctx, params, optFns
func (_m *Pricing) GetProducts(ctx context.Context, params *servicepricing.GetProductsInput, optFns ...func(*servicepricing.Options)) (*servicepricing.GetProductsOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 *servicepricing.GetProductsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *servicepricing.GetProductsInput, ...func(*servicepricing.Options)) (*servicepricing.GetProductsOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *servicepricing.GetProductsInput, ...func(*servicepricing.Options)) *servicepricing.GetProductsOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicepricing.GetProductsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *servicepricing.GetProductsInput, ...func(*servicepricing.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Pricing_GetProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProducts'
type Pricing_GetProducts_Call struct {
	*mock.Call
}

// GetProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - params *servicepricing.GetProductsInput
//   - optFns ...func(*servicepricing.Options)
func (_e *Pricing_Expecter) GetProducts(ctx interface{}, params interface{}, optFns ...interface{}) *Pricing_GetProducts_Call {
	return &Pricing_GetProducts_Call{Call: _e.mock.On("GetProducts",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Pricing_GetProducts_Call) Run(run func(ctx context.Context, params *servicepricing.GetProductsInput, optFns ...func(*servicepricing.Options))) *Pricing_GetProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*servicepricing.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*servicepricing.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*servicepricing.GetProductsInput), variadicArgs...)
	})
	return _c
}

func (_c *Pricing_GetProducts_Call) Return(_a0 *servicepricing.GetProductsOutput, _a1 error) *Pricing_GetProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Pricing_GetProducts_Call) RunAndReturn(run func(context.Context, *servicepricing.GetProductsInput, ...func(*servicepricing.Options)) (*servicepricing.GetProductsOutput, error)) *Pricing_GetProducts_Call {
	_c.Call.Return(run)
	return _c
}

// NewPricing creates a new instance of Pricing. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPricing(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pricing {
	mock := &Pricing{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
