{
 "title": "CloudCost Exporter Operations Dashboard",
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(tanka_environment_info{app=\"cloudcost-exporter\"},exported_cluster)"
   },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Collector Status",
   "type": "stat",
   "description": "Display the status of all the collectors running.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (provider, collector) (cloudcost_exporter_collector_last_scrape_error == 0)",
     "legendFormat": "{{provider}}:{{collector}}"
    }
   ]
  },
  {
   "title": "Image Versions by Cluster",
   "type": "table",
   "description": "Shows which cloudcost-exporter image version is deployed on each cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count by (cluster, image_version) (label_replace(kube_pod_container_info{container=\"cloudcost-exporter\"}, \"image_version\", \"$2\", \"image\", \"(.*:)(.*)\"))"
    }
   ]
  },
  {
   "title": "Collector Scrape Duration",
   "type": "timeseries",
   "description": "Duration of scrapes by provider and collector",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cloudcost_exporter_collector_last_scrape_duration_seconds",
     "legendFormat": "{{provider}}:{{collector}}"
    }
   ]
  },
  {
   "title": "CloudCost Exporter Logs",
   "type": "logs",
   "description": "Application logs for cloudcost-exporter, filtered by cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\", namespace=\"cloudcost-exporter\"}"
    }
   ]
  },
  { "title": "AWS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CostExplorer API Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (increase(cloudcost_exporter_aws_s3_cost_api_requests_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next pricing map refresh",
   "type": "timeseries",
   "description": "The AWS s3 module uses cost data pulled from Cost Explorer, which costs $0.01 per API call. The cost metrics are refreshed every hour, so if this value goes below 0, it indicates a problem with refreshing the pricing map and thus needs investigation.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (cluster) (cloudcost_exporter_aws_s3_next_scrape{cluster=~\"$cluster\"}) - time() ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "GCS List Buckets Requests Per Second",
   "type": "timeseries",
   "description": "The number of requests per second to list buckets in GCS.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster, status) (increase(cloudcost_exporter_gcp_gcs_bucket_list_status_total[5m]))",
     "legendFormat": "{{cluster}}:{{status}}"
    }
   ]
  },
  {
   "title": "GCS Pricing Map Refresh Time",
   "type": "timeseries",
   "description": "The amount of time before the next refresh of the GCS pricing map. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (cluster) (cloudcost_exporter_gcp_gcs_next_scrape{cluster=~\"$cluster\"}) - time() ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}