// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetOperationsDiscounts provides a mock function with given fields:
func (_m *Service) GetOperationsDiscounts() map[string]map[string]map[string]float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOperationsDiscounts")
	}

	var r0 map[string]map[string]map[string]float64
	if rf, ok := ret.Get(0).(func() map[string]map[string]map[string]float64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]map[string]float64)
		}
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
